name: CI

on:
  push:
    branches:    
      - 'main'

  pull_request:
    branches:
      - 'main'

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Render with latest data
        run: |
            deno run --reload src/index.ts
            deno run --allow-read --allow-write src/index.ts --render

      # Events triggered by the GITHUB_TOKEN will not create a new workflow run
      - name: Update Repo
        run: |
            ls -ls .husky
            chmod +x .husky/repo-update.sh
            bash .husky/repo-update.sh
