on:
  issues:
    types: [opened]

jobs:
  pre_job:
    name: Pre Job
    runs-on: ubuntu-latest

    if: startsWith(github.event.issue.title, 'ttt_move_') && endsWith(github.event.issue.title, '_') && contains(github.event.issue.labels.*.name, 'make move')

    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}

    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          concurrent_skipping: 'same_content_newer'

  skip:
    name: Skipped
    needs: [pre_job]
    runs-on: ubuntu-latest
    
    if: needs.pre_job.outputs.should_skip == 'true'

    steps:
      - run: echo "As there is another request processing, we cannot take yours."

      - name: Issue Resolved
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          state: 'closed'

  game:
    name: Game
    needs: [pre_job]
    runs-on: ubuntu-latest

    if: needs.pre_job.outputs.should_skip != 'true'

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Set env vars
        run: |
            title=${{ github.event.issue.title }}
            regex="^_ttt_move_[abcABC][123]_(|[:\'.]{9})_$"

            if [[ $title =~ $regex ]]; then
                echo "MOVE=${title:10:2}" >> $GITHUB_ENV
                echo "SLF=${title:13:9}" >> $GITHUB_ENV
            else
                echo "Format got changed, it must follow '$regex'."
                exit 1
            fi

            echo "EVENT_USER_URL=${{ github.event.issue.user.html_url }}" >> $GITHUB_ENV
            echo "EVENT_USER_NAME=${{ github.event.issue.user.login }}" >> $GITHUB_ENV
            echo "HELLO=TEST_buddy_TEST" >> $GITHUB_ENV

      - name: Making your move
		run: |
            deno run --reload src/index.ts
		    deno run --allow-read --allow-write src/index.ts --game --name="$EVENT_USER_NAME" --url="$EVENT_USER_URL" --moveTo="$MOVE" --slf="$SLF"

      - name: Updating README.md
		run: |
		    chmod +x .husky/repo-update.sh
            bash .husky/repo-update.sh

      - name: Issue Resolved
        if: ${{ always() }}
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          state: 'closed'
