on:
  issues:
    types: [opened]

jobs:
  pre_job:
    name: Pre Job
    runs-on: ubuntu-latest

    if: startsWith(github.event.issue.title, 'ttt_move_') && endsWith(github.event.issue.title, '_') && contains(github.event.issue.labels.*.name, 'make move')

    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}

    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          concurrent_skipping: 'same_content_newer'

  skip:
    name: Skipped
    needs: [pre_job]
    runs-on: ubuntu-latest
    
    if: needs.pre_job.outputs.should_skip == 'true'

    steps:
      - run: echo "As there is another request processing, we cannot take yours."

      - name: Issue Resolved
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          state: 'closed'

  game:
    name: Game
    needs: [pre_job]
    runs-on: ubuntu-latest

    if: needs.pre_job.outputs.should_skip != 'true'

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: Title echo ${{ github.event.issue.title }}
      - run: User name echo ${{ github.event.issue.user.login }}
      - run: User Url ${{ github.event.issue.user.html_url }}

      - name: Issue Resolved
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          state: 'closed'